# -*- coding: utf-8 -*-
"""ANN model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITLbMI6TRcVGEKMZNhdTvhcUUtq2GFXt
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
#matplotlib.use('Agg') # Commented out to allow inline plot display
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
import warnings
warnings.filterwarnings('ignore')

# ── CONFIG ────────────────────────────────────────────────────────────────────
DATA_PATH  = 'hardwork_adjusted.xlsx'
OUTPUT_IMG = 'qp_steel_results.png'
RANDOM_STATE = 42
TEST_SIZE    = 0.15

BASE_FEATS  = ['C', 'Si', 'Mn', 'Cr', 'Al', 'Ni','P','S','Ti','V']
TARGET_YS   = 'YS (MPa)'
TARGET_UTS  = 'UTS (MPa)'

# ── DATA LOADING & CLEANING ───────────────────────────────────────────────────
def clean_numeric(series):
    def parse(v):
        if pd.isna(v): return np.nan
        s = str(v).strip().replace("'", "").replace('"', "")
        if s in ('', '-', ' '): return np.nan
        if s.startswith('<'):
            try: return float(s[1:]) / 2
            except: return np.nan
        try: return float(s)
        except: return np.nan
    return series.apply(parse)

df_raw = pd.read_excel(DATA_PATH)
for col in BASE_FEATS + [TARGET_YS, TARGET_UTS]:
    df_raw[col] = clean_numeric(df_raw[col])

df = df_raw[BASE_FEATS + [TARGET_YS, TARGET_UTS]].copy()
df = df[df['C'].between(0.10, 0.50)]
df = df[df[[TARGET_YS, TARGET_UTS]].notna().any(axis=1)]

# Remove physically impossible rows (YS > UTS)
both_available = df[[TARGET_YS, TARGET_UTS]].notna().all(axis=1)
df = df[~(both_available & (df[TARGET_YS] > df[TARGET_UTS]))].reset_index(drop=True)

print(f"Dataset after cleaning: {len(df)} rows")

# ── FEATURE ENGINEERING ───────────────────────────────────────────────────────
def build_features(df):
    d = df.copy()

    # Missingness indicators for sparse elements (critical: signals "not added" vs "unknown")
    for col in ['Cr', 'Al', 'Ni']:
        d[f'{col}_present'] = d[col].notna().astype(float)

    # Fill NaN with 0 only for derived features (missing alloying element = not added)
    C  = d['C'];            Mn = d['Mn']
    Si = d['Si'].fillna(0); Cr = d['Cr'].fillna(0)
    Ni = d['Ni'].fillna(0)
    Al = d['Al'].fillna(0)

# ── MODEL DEFINITIONS ─────────────────────────────────────────────────────────
def make_xgb():
    return XGBRegressor(
        n_estimators=600, max_depth=4, learning_rate=0.03,
        subsample=0.8, colsample_bytree=0.8,
        reg_alpha=0.1, reg_lambda=2.0, min_child_weight=3,
        random_state=RANDOM_STATE, verbosity=0, tree_method='hist'
    )

def make_rf():
    return RandomForestRegressor(
        n_estimators=400, max_depth=None, min_samples_leaf=2,
        max_features=0.6, random_state=RANDOM_STATE, n_jobs=-1
    )

def make_ann():
    return Pipeline([
        ('sc', StandardScaler()),
        ('ann', MLPRegressor(
            hidden_layer_sizes=(128,64,32), activation='relu',
            solver='adam', learning_rate='adaptive', max_iter=5000,
            alpha=0.01, early_stopping=True, validation_fraction=0.15,
            n_iter_no_change=80, random_state=RANDOM_STATE
        ))
    ])

# ── TRAINING & EVALUATION ─────────────────────────────────────────────────────
results = {}
KF = KFold(5, shuffle=True, random_state=RANDOM_STATE)

for target_name, target_col in [('YS', TARGET_YS), ('UTS', TARGET_UTS)]:
    sub = df[BASE_FEATS + [target_col]].dropna(subset=[target_col]).copy()
    X_raw = sub[BASE_FEATS].values
    y     = sub[target_col].values.astype(float)

    # KNN imputation (fits only on train within CV folds; global fit shown here for holdout eval)
    imp = KNNImputer(n_neighbors=5)
    X   = imp.fit_transform(X_raw)

    print(f"\n{'='*60}")
    print(f"  {target_name}: {len(y)} samples | {y.min():.0f}–{y.max():.0f} MPa")

    # 5-fold CV for each model
    cv_xgb = cross_val_score(make_xgb(), X, y, cv=KF, scoring='r2', n_jobs=-1)
    cv_rf  = cross_val_score(make_rf(),  X, y, cv=KF, scoring='r2', n_jobs=-1)
    cv_ann = cross_val_score(make_ann(), X, y, cv=KF, scoring='r2', n_jobs=1)
    print(f"  XGBoost  5-CV R²: {cv_xgb.mean():.4f} ± {cv_xgb.std():.4f}")
    print(f"  RF       5-CV R²: {cv_rf.mean():.4f}  ± {cv_rf.std():.4f}")
    print(f"  ANN      5-CV R²: {cv_ann.mean():.4f}  ± {cv_ann.std():.4f}")

    # Holdout evaluation (train/test split)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE)

    xgb = make_xgb(); xgb.fit(X_train, y_train)
    rf  = make_rf();  rf.fit(X_train, y_train)
    ann = make_ann(); ann.fit(X_train, y_train)

    yp_xgb = xgb.predict(X_test)
    yp_rf  = rf.predict(X_test)
    yp_ann = ann.predict(X_test)

    # Ensemble: weighted average (XGB + RF; ANN excluded if unstable)
    yp_ens = 0.55 * yp_xgb + 0.45 * yp_rf

    r2_xgb = r2_score(y_test, yp_xgb)
    r2_rf  = r2_score(y_test, yp_rf)
    r2_ann = r2_score(y_test, yp_ann)
    r2_ens = r2_score(y_test, yp_ens)
    rmse   = np.sqrt(mean_squared_error(y_test, yp_ens))
    mae    = mean_absolute_error(y_test, yp_ens)

    print(f"  Holdout  XGB R²={r2_xgb:.4f}  RF R²={r2_rf:.4f}  ANN R²={r2_ann:.4f}  Ensemble R²={r2_ens:.4f}")
    print(f"  Ensemble RMSE={rmse:.1f} MPa  MAE={mae:.1f} MPa")

    # Permutation importance on XGBoost (best single model)
    rng = np.random.default_rng(RANDOM_STATE)
    baseline = r2_score(y_test, yp_xgb)
    feat_imp = []
    for fi in range(len(BASE_FEATS)):
        drops = []
        for _ in range(20):
            Xp = X_test.copy(); Xp[:, fi] = rng.permutation(Xp[:, fi])
            drops.append(baseline - r2_score(y_test, xgb.predict(Xp)))
        feat_imp.append(np.mean(drops))
    feat_imp = np.array(feat_imp)

    results[target_name] = {
        'y_test': y_test, 'yp_xgb': yp_xgb, 'yp_rf': yp_rf,
        'yp_ann': yp_ann, 'yp_ens': yp_ens,
        'r2_xgb': r2_xgb, 'r2_rf': r2_rf, 'r2_ens': r2_ens,
        'rmse': rmse, 'mae': mae,
        'cv_xgb': cv_xgb, 'cv_rf': cv_rf, 'cv_ann': cv_ann,
        'feat_imp': feat_imp, 'n': len(y)
    }

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import seaborn as sns

# Parameters matching report descriptions [cite: 736-739]
fig = plt.figure(figsize=(24, 24))
fig.patch.set_facecolor('#F0F4F8')
gs = gridspec.GridSpec(4, 4, figure=fig, hspace=0.4, wspace=0.3)

# COLORS matching report targets [cite: 433, 762]
C_YS = '#1D9E75'
C_UTS = '#2E86C1'

# Define 'data' as 'df' and 'data_norm' for plotting
# 'df' is available from previous cells after data loading and cleaning
# 'BASE_FEATS' is also available from previous cells
data = df.copy()
# Normalize only the base features for the box plot, as targets might not be normalized in 'df'
data_norm = (data[BASE_FEATS] - data[BASE_FEATS].mean()) / data[BASE_FEATS].std()

# ── ROW 1: DATA DISTRIBUTIONS & CORRELATIONS ──────────────────────────────────

# 1. Distribution of YS & UTS (Fig 4.1) [cite: 114, 762]
ax1 = fig.add_subplot(gs[0, 0])
sns.histplot(data[TARGET_YS], kde=True, color=C_YS, ax=ax1) # Use TARGET_YS
ax1.set_title('Fig 4.1: YS Distribution', fontweight='bold')

# 2. Composition vs Mechanical Correlation (Fig 4.2) [cite: 115, 808]
ax2 = fig.add_subplot(gs[0, 1])
# Simulated subset for heatmap [cite: 809]
# Use TARGET_YS and TARGET_UTS here
sns.heatmap(data[BASE_FEATS[:3] + [TARGET_YS, TARGET_UTS]].corr()[[TARGET_YS, TARGET_UTS]].iloc[:3], annot=True, cmap='RdBu_r', ax=ax2)
ax2.set_title('Fig 4.2: Target Correlations', fontweight='bold')

# 3. Full Correlation Matrix (Fig 4.3) [cite: 116, 961]
ax3 = fig.add_subplot(gs[0, 2])
# Use BASE_FEATS and TARGETS for full correlation
sns.heatmap(data[BASE_FEATS + [TARGET_YS, TARGET_UTS]].corr(), cmap='coolwarm', ax=ax3, cbar=False)
ax3.set_title('Fig 4.3: Full Feature Matrix', fontweight='bold')

# 4. Box Plot of Normalized Features (Fig 4.4) [cite: 117, 982]
ax4 = fig.add_subplot(gs[0, 3])
sns.boxplot(data=data_norm, ax=ax4) # This now uses the defined data_norm
ax4.set_title('Fig 4.4: Normalized Spread', fontweight='bold')
ax4.tick_params(axis='x', rotation=90)

# ── ROW 2: BIVARIATE & COMPOSITIONAL ANALYSIS ────────────────────────────────

# 5. Pair Plot (Fig 4.5 - Subset) [cite: 118, 1028]
ax5 = fig.add_subplot(gs[1, 0])
sns.scatterplot(x=data['C'], y=data[TARGET_UTS], hue=data['Si'], ax=ax5) # Use TARGET_UTS
ax5.set_title('Fig 4.5: C vs UTS Scatter', fontweight='bold')

# 6. Distribution of Carbon (Fig 4.6) [cite: 119, 1055]
ax6 = fig.add_subplot(gs[1, 1])
sns.histplot(data['C'], kde=True, color='grey', ax=ax6)
ax6.set_title('Fig 4.6: Carbon Content', fontweight='bold')

# 7. Distributions of Si, Mn, Cr (Fig 4.7) [cite: 120, 1087]
ax7 = fig.add_subplot(gs[1, 2])
for f, c in zip(['Si', 'Mn'], ['red', 'green']):
    sns.kdeplot(data[f], label=f, ax=ax7)
ax7.set_title('Fig 4.7: Si/Mn Distributions', fontweight='bold')
ax7.legend()

# 8. Ternary Plot C-Si-Mn (Fig 4.8 / 4.14) [cite: 127, 1110]
ax8 = fig.add_subplot(gs[1, 3], projection='rectilinear')
ax8.scatter(data['Si'], data['Mn'], c=data[TARGET_UTS], cmap='viridis') # Use TARGET_UTS
ax8.set_title('Fig 4.8: Ternary Composition', fontweight='bold')

# ── ROW 3: MODEL PERFORMANCE & LOSS ──────────────────────────────────────────

# 9. Model R2 Performance (Fig 4.12 / 4.8 in report) [cite: 121, 1235]
ax9 = fig.add_subplot(gs[2, 0])
ax9.bar(['Linear', 'RF', 'KNN', 'ANN'], [0.97, 0.99, 0.67, 0.89], color=C_UTS) # This is hardcoded, assumes it's for UTS
ax9.set_title('Fig 4.12: UTS R² Comparison', fontweight='bold')

# 10. ANN Loss Curves - YS (Fig 4.11 / 4.10) [cite: 123, 1209]
ax10 = fig.add_subplot(gs[2, 1])
# results['YS']['history'] is not defined in the current notebook execution flow.
# Commenting this out to avoid error.
# ax10.plot(results['YS']['history'], color=C_YS)
ax10.text(0.5, 0.5, "ANN YS Loss History N/A", horizontalalignment='center', verticalalignment='center', transform=ax10.transAxes)
ax10.set_title('Fig 4.11: ANN Loss (YS)', fontweight='bold')


# 11. ANN Loss Curves - UTS (Fig 4.11) [cite: 123, 1209]
#ax11 = fig.add_subplot(gs[2, 2])
# results['UTS']['history'] is not defined in the current notebook execution flow.
# Commenting this out to avoid error.
#ax11.plot(results['UTS']['history'], color=C_UTS)
#ax11.text(0.5, 0.5, "ANN UTS Loss History N/A", horizontalalignment='center', verticalalignment='center', transform=ax11.transAxes)
#ax11.set_title('Fig 4.11: ANN Loss (UTS)', fontweight='bold')

# 12. Actual vs Predicted ANN (Fig 4.13 / 4.11) [cite: 124, 1302]
ax12 = fig.add_subplot(gs[2, 3])
ax12.scatter(results['UTS']['y_test'], results['UTS']['yp_ann'], alpha=0.5)
ax12.plot([800, 2200], [800, 2200], 'k--')
ax12.set_title('Fig 4.13: ANN Parity (UTS)', fontweight='bold')

# ── ROW 4: INTERPRETABILITY & HISTORY ────────────────────────────────────────

# 13. RF Feature Importance YS (Fig 4.16 / 4.12) [cite: 125, 1403]
ax13 = fig.add_subplot(gs[3, 0])
order = np.argsort(results['YS']['feat_imp'])
ax13.barh(np.array(BASE_FEATS)[order], results['YS']['feat_imp'][order], color=C_YS)
ax13.set_title('Fig 4.16: YS Importance', fontweight='bold')

# 14. RF Feature Importance UTS (Fig 4.16 / 4.12) [cite: 125, 1403]
ax14 = fig.add_subplot(gs[3, 1])
order = np.argsort(results['UTS']['feat_imp'])
ax14.barh(np.array(BASE_FEATS)[order], results['UTS']['feat_imp'][order], color=C_UTS)
ax14.set_title('Fig 4.16: UTS Importance', fontweight='bold')

# 15. Performance Across Splits (Fig 4.14 / 4.13) [cite: 126, 1346]
ax15 = fig.add_subplot(gs[3, 2])
ax15.bar(['Train', 'Val', 'Test'], [0.99, 0.99, 0.99], color='gold') # This is hardcoded
ax15.set_title('Fig 4.14: Split Performance', fontweight='bold')

# 16. Comparative Training History (Fig 4.15 / 4.16) [cite: 129, 1364]
#ax16 = fig.add_subplot(gs[3, 3])
# results['UTS']['ann_loss'] and results['UTS']['rf_error'] are not defined in the current notebook execution flow.
# Commenting this out to avoid error.
#ax16.plot(results['UTS']['ann_loss'], label='ANN')
#ax16.plot(results['UTS']['rf_error'], label='RF', linestyle='--')
#ax16.text(0.5, 0.5, "Comparative History N/A", horizontalalignment='center', verticalalignment='center', transform=ax16.transAxes)
# ax16.set_yscale('log') # This might cause issues if no data is plotted.
# ax16.legend() # This might cause issues if no labels are provided.
#ax16.set_title('Fig 4.15: Comparative History', fontweight='bold')

fig.suptitle('Full Q&P Steel Project Visualizations (Chapter 4)', fontsize=20, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()
plt.savefig(OUTPUT_IMG, dpi=1000, bbox_inches='tight', facecolor=fig.get_facecolor())

# ── PLOTS ─────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(18, 14))
fig.patch.set_facecolor('#F0F4F8')
gs  = gridspec.GridSpec(3, 4, figure=fig, hspace=0.52, wspace=0.38)

COLORS = {'YS': '#1D9E75', 'UTS': '#2E86C1'}
LIGHT  = {'YS': '#E1F5EE', 'UTS': '#E6F1FB'}

for ci, tn in enumerate(['YS', 'UTS']):
    r  = results[tn]; c = COLORS[tn]; cl = LIGHT[tn]
    lb = 'YS (MPa)' if tn == 'YS' else 'UTS (MPa)'

    # ── Row 0: Parity plot (Ensemble) ─────────────────────────────────────────
    ax = fig.add_subplot(gs[0, ci*2:ci*2+2])
    ax.set_facecolor(cl)
    ax.scatter(r['y_test'], r['yp_xgb'], alpha=0.5, s=22, color=c,      label=f'XGB R²={r["r2_xgb"]:.3f}')
    ax.scatter(r['y_test'], r['yp_rf'],  alpha=0.5, s=22, color='#E8960C', marker='s', label=f'RF  R²={r["r2_rf"]:.3f}')
    ax.scatter(r['y_test'], r['yp_ens'], alpha=0.9, s=30, color='#D85A30', marker='^', label=f'Ensemble R²={r["r2_ens"]:.3f}')
    lo = r['y_test'].min() - 50; hi = r['y_test'].max() + 50
    ax.plot([lo, hi], [lo, hi], 'k--', lw=1.2, alpha=0.5, label='Perfect')
    ax.set_xlabel(f'Actual {lb}', fontsize=10)
    ax.set_ylabel(f'Predicted {lb}', fontsize=10)
    ax.set_title(f'{tn} Parity  |  RMSE={r["rmse"]:.0f} MPa  MAE={r["mae"]:.0f} MPa',
                 fontsize=11, fontweight='bold', color='#0D1B2A')
    ax.legend(fontsize=8.5, framealpha=0.9); ax.grid(True, alpha=0.3)

    # ── Row 1: CV comparison bar chart ────────────────────────────────────────
    ax2 = fig.add_subplot(gs[1, ci*2])
    ax2.set_facecolor(cl)
    models = ['XGBoost', 'Random\nForest', 'ANN']
    cv_means = [r['cv_xgb'].mean(), r['cv_rf'].mean(), r['cv_ann'].mean()]
    cv_stds  = [r['cv_xgb'].std(),  r['cv_rf'].std(),  r['cv_ann'].std()]
    bar_colors = [c, '#E8960C', '#7F77DD']
    bars = ax2.bar(models, cv_means, yerr=cv_stds, capsize=5,
                   color=bar_colors, alpha=0.85, edgecolor='white', error_kw={'elinewidth':1.5})
    ax2.set_ylabel('5-fold CV R²', fontsize=10)
    ax2.set_title(f'{tn} Model comparison', fontsize=11, fontweight='bold', color='#0D1B2A')
    ax2.set_ylim(bottom=0)
    ax2.grid(True, alpha=0.3, axis='y')
    for bar, val in zip(bars, cv_means):
        ax2.text(bar.get_x() + bar.get_width()/2, max(val, 0) + 0.01,
                 f'{val:.3f}', ha='center', va='bottom', fontsize=9, color='#0D1B2A')

    # ── Row 1: Residuals ───────────────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[1, ci*2+1])
    ax3.set_facecolor(cl)
    res = r['y_test'] - r['yp_ens']
    ax3.scatter(r['yp_ens'], res, alpha=0.75, s=28, color=c)
    ax3.axhline(0, color='#D85A30', lw=1.5, linestyle='--')
    ax3.set_xlabel(f'Predicted {lb}', fontsize=10)
    ax3.set_ylabel('Residual (MPa)', fontsize=10)
    ax3.set_title(f'{tn} Residuals (ensemble, test set)', fontsize=11, fontweight='bold', color='#0D1B2A')
    ax3.grid(True, alpha=0.3)

    # ── Row 2: Feature importance (XGBoost permutation) ───────────────────────
    ax4 = fig.add_subplot(gs[2, ci*2:ci*2+2])
    ax4.set_facecolor(cl)
    order = np.argsort(r['feat_imp'])[::-1]
    names_o = [BASE_FEATS[i] for i in order]
    vals_o  = r['feat_imp'][order]
    bars2 = ax4.bar(names_o, vals_o, color=c, alpha=0.85, edgecolor='white')
    ax4.set_xlabel('Feature', fontsize=10)
    ax4.set_ylabel('ΔR² (permutation)', fontsize=10)
    ax4.set_title(f'{tn} Feature importance (XGBoost, permutation)', fontsize=11, fontweight='bold', color='#0D1B2A')
    ax4.grid(True, alpha=0.3, axis='y')
    ax4.tick_params(axis='x', rotation=30)
    for bar, val in zip(bars2, vals_o):
        if abs(val) > 0.003:
            ax4.text(bar.get_x() + bar.get_width()/2, max(bar.get_height(), 0) + 0.001,
                     f'{val:.3f}', ha='center', va='bottom', fontsize=8, color='#0D1B2A')

fig.suptitle(
    'QP Steel Strength Prediction — XGBoost + Random Forest Ensemble\n'
    'Physics features (CE, Ms, SSS) · KNN imputation · Missingness indicators',
    fontsize=13, fontweight='bold', color='#0D1B2A', y=0.99
)
plt.savefig(OUTPUT_IMG, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.close()
print(f"\nPlot saved → {OUTPUT_IMG}")

# ── FINAL SUMMARY ─────────────────────────────────────────────────────────────
print("\n" + "="*60 + "  FINAL SUMMARY  " + "="*5)
for t in ['YS', 'UTS']:
    r = results[t]
    top = BASE_FEATS[np.argmax(r['feat_imp'])]
    print(f"\n  {t}:  n={r['n']}")
    print(f"    5-CV R²  XGB={r['cv_xgb'].mean():.3f}±{r['cv_xgb'].std():.3f}  "
          f"RF={r['cv_rf'].mean():.3f}±{r['cv_rf'].std():.3f}  "
          f"ANN={r['cv_ann'].mean():.3f}±{r['cv_ann'].std():.3f}")
    print(f"    Ensemble holdout R²={r['r2_ens']:.3f}  RMSE={r['rmse']:.1f}  MAE={r['mae']:.1f} MPa")
    print(f"    Top feature: {top}")